artifacts_root: ./artifacts

data_ingestion:
  root_dir: ./artifacts/data_ingestion
  source_data_dir: ./brain-tumor-dataset


prepare_base_model:
  root_dir: ./artifacts/prepare_base_model
  base_model_path: ./artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: ./artifacts/prepare_base_model/base_model_updated.pth


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: ./artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: ./artifacts/prepare_callbacks/checkpoint_dir/model.pth


training:
  root_dir: ./artifacts/training
  trained_model_path: ./artifacts/training/model.pth